#! /bin/sh
# /etc/init.d/checkconnection

### BEGIN INIT INFO
# Provides:          wifi connection checker
# Required-Start:    $network $syslog
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script from www.stuffaboutcode.com which will start / stop a program a boot / shutdown.
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting wifi connection checker"
    /usr/bin/checkconnection &
    ;;
  stop)
    echo "Stopping wifi connection checker"
    killall checkconnection
    ;;
  *)
    echo "Usage: /etc/init.d/noip {start|stop}"
    exit 1
    ;;
esac

exit 0 
